[package]
name = "rust_lib_cunda_flutter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
chrono = "0.4.42"
flutter_rust_bridge = "=2.11.1"
log = "0.4.28"
tokio = { version = "1.48.0", features = ["time", "rt"] }
postcard = { version = "1.1.2", features = ["alloc"] }
postcard-rpc = { version = "0.12.0", features = ["use-std"] }
postcard-schema = "0.2.5"
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
cobs = { version = "0.5.0" }
pastey = { version = "*" }
protocol = { path = "../../protocol", features = [
    "flutter",
] } # Endpoint and Topic definitions
frb_prpc_juggle = { path = "../../frb_prpc_juggle" }
rand = "0.9.2"
env_logger = "0.11.8"


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
